

var app = angular.module('assetApp', ['ngRoute','ngTouch']);

app.factory('AssetCodeMake', ['$http',function ($http, code) {
	var make = {
		APPRO13CO:"Apple",
		APPRO15CO:"Apple",
		APRO15RCO:"Apple",
		APRO13RCO:"Apple",
		APAIR13CO:"Apple",
		APCMINICO:"Apple",
		AP27MO:"Apple",
		DEX7010CO:"Dell",
		DEEX790CO:"Dell",
		DEE6530CO:"Dell",
		DEE6520CO:"Dell",
		DEEX780CO:"Dell",
		DENCH19MO:"Dell",
		DENCH24MO:"Dell",
		DE55CDNPR:"Dell",
		DE130CNPR:"Dell",
		DE460DNPR:"Dell",
		DE760DNPR:"Dell",
		DE350DNPR:"Dell",
		DE5230NPR:"Dell",
		LOMK710KE:"Logitech",
		LOM705KE:"Logitech",
		LOK350KE:"Logitech",
		LOM110KE:"Logitech",
		NE105NASW:"Netgear",
		NEFS105SW:"Netgear",
		PLVISTAAM:"Plantronics",
		PLHW261HE:"Plantronics",
		POIP321PH:"Polycom",
		POIP601PH:"Polycom",
		POP5000PH:"Polycom",
		POIP320PH:"Polycom",
		POIP355PH:"Polycom",
		SHUOS60DA:"Sharp",
		SOVIA42DA:"Sony",
		DEDVI2DO:"Dell",
		DEDVI1DO:"Dell",
		DETABLECH:"Dell",
		SAART55DA:"Samsung",
		POIP650PH:"Polycom",
		APRBOLTMO:"Apple",
		APMAC21CO:"Apple",
		APMAC27CO:"Apple",
		BOBOOKCO:"BOOK",
		DET3500CO:"Dell",
		DET7500CO:"Dell",
		APACPROCO:"Apple",
		DET1650CO:"Dell",
		APAIR11CO:"Apple",
		DEER720SE:"Dell",
		DEK1100SE:"Dell",
		DEE1950SE:"Dell",
		DEER510SE:"Dell",
		DEK2100SE:"Dell",
		DEER610SE:"Dell",
		DED1000SE:"Dell",
		DEE2950SE:"Dell",
		HPDL360SE:"HP",
		DE6110XSE:"Dell",
		DEE2850SE:"Dell",
		DE3200ISE:"Dell",
		DET1700CO:"Dell",
		PLM22A:"Plantronics",
		AMB13L:"Apple",
		AMB15L:"Apple",
		AMBP15RL:"Apple",
		AMBP13RL:"Apple",
		AMBA13L:"Apple",
		AMMD:"Apple",
		DO7010D:"Dell",
		DO790D:"Dell",
		DE6530CO:"Dell",
		DE6520CO:"Dell",
		DO780D:"Dell",
		SBrav42DB:"Sony",
		SHaqu60DB:"Sharp",
		PLM261H:"Plantronics",
		LMK700K:"Logitech",
		LM705MO:"Logitech",
		LK350K:"Logitech",
		LM110MO:"Logitech",
		A27M:"Apple",
		D19M:"Dell",
		D24M:"Dell",
		P321PH:"Polycom",
		P601PH:"Polycom",
		P5000PH:"Polycom",
		D2155PR:"Dell",
		D3130PR:"Dell",
		DB3460PR:"Dell",
		DC3760dnPR:"Dell",
		D5350dnPR:"Dell",
		D5230nPR:"Dell",
		NGS105S:"Netgear",
		NFS105S:"Netgear",
		DT1650D:"Dell",
		p320ph:"Polycom",
		LON231WE:"Logitech"


		};
	return { 
		returnmake: function(code){
			
			return make[code];
		}
	}

	
}]);
app.factory('AssetCodeModel', [function (code) {
	var Model ={
		APRO15RCO:"MACBookPro15R",
		APRO13RCO:"MACBookPro13R",
		APAIR13CO:"MacBookAir13",
		APCMINICO:"MacMini",
		AP27SW:"27",
		DEX7010CO:"Optiplex7010",
		DEEX790CO:"Optiplex790",
		DEE6530CO:"LatitudeE6530",
		DEE6520CO:"LatitudeE6520",
		DEEX780CO:"Optiplex780",
		DENCH19MO:"inch19",
		DENCH24MO:"inch24",
		DE55CDNPR:"2155cdn",
		DE130CNPR:"3130cn",
		DE460DNPR:"B3460dn",
		DE760DNPR:"C3760dn",
		DE350DNPR:"5350dn",
		DE5230NPR:"5230n",
		DET1650CO:"T1650",
		LOMK710KE:"MK700/MK710",
		LOM705KE:"M705",
		LOK350KE:"K350",
		LOM110KE:"M110",
		NE105NASW:"GS105NA",
		NEFS105SW:"FS105",
		PLVISTAAM:"M22Vista",
		PLHW261HE:"HW261",
		POIP321PH:"IP321",
		POIP601PH:"IP601",
		POP5000PH:"IP5000",
		POIP320PH:"IP320",
		POIP355PH:"IP355",
		SHUOS60DA:"Aquos60",
		SOVIA42DA:"Bravia42",
		DEDVI2DO:"DVI2",
		DEDVI1DO:"DVI1",
		DETABLECH:"Portable",
		SAART55DA:"Smart55",
		POIP650PH:"IP650",
		POIP650PH:"IP650",
		APRBOLTMO:"27Thunderbolt",
		APMAC21CO:"IMAC21",
		APMAC27CO:"Imac27",
		BOBOOKCO:"Book",
		DET3500CO:"PrecisionT3500",
		DET7500CO:"PrecisionT7500",
		APACPROCO:"MacPRO",
		DET1650CO:"PrecisionT1650",
		APAIR11CO:"MacAir11",
		DEER720SE:"PoweredgeR720",
		DEK1100SE:"K1100",
		DEE1950SE:"Poweredge1950",
		DEER510SE:"PoweredgeR510",
		DEK2100SE:"K2100",
		DEER610SE:"PoweredgeR610",
		DED1000SE:"PowerVault MD1000",
		DEE2950SE:"PowerEdge2950",
		HPDL360SE:"ProliantDL360",
		DE6110XSE:"EquallogicPS6110X",
		DEE2850SE:"PowerEdge2850",
		DE3200ISE:"PowervaultMD3200i",
		DET1700CO:"PrecisionT1700",
		PLM22A:"M22Vista",
		AMB13L:"MACBookPro13",
		AMB15L:"MACBookPro15 ",
		AMBP15RL:"MACBookPro15R",
		AMBP13RL:"MACBookPro13R",
		AMBA13L:"MacBookAir13",
		AMMD:"MacMini",
		DO7010D:"Optiplex7010",
		DO790D:"Optiplex790",
		DE6530CO:"LatitudeE6530",
		DE6520CO:"LatitudeE6520",
		DO780D:"Optiplex780",
		SBrav42DB:"Bravia42",
		SHaqu60DB:"Aquos60",
		PLM261H:"HW261",
		LMK700K:"MK700/MK710",
		LM705MO:"M705",
		LK350K:"K350",
		LM110MO:"M110",
		A27M:"27",
		D19M:"inch19",
		D24M:"inch24",
		P321PH:"IP321",
		P601PH:"IP601",
		P5000PH:"IP5000",
		D2155PR:"2155cdn",
		D3130PR:"3130cn",
		DB3460PR:"B3460dn",
		DC3760dnPR:"C3760dn",
		D5350dnPR:"5350dn",
		D5230nPR:"5230n",
		NGS105S:"GS105NA",
		NFS105S:"FS105",
		DT1650D:"T1650",
		p320ph:"IP320",
		LON231WE:"N231"



	};

return { 
		returnmodel: function(code){
			return Model[code];
		}
	}

	
}]);
app.factory('AssetCodeType', [function (code) {
	var Type ={
		APRO15RCO:"Computer",
		APRO13RCO:"Computer",
		APAIR13CO:"Computer",
		APCMINICO:"Computer",
		AP27SW:"Switch",
		DEX7010CO:"Computer",
		DEEX790CO:"Computer",
		DEE6530CO:"Computer",
		DEE6520CO:"Computer",
		DEEX780CO:"Computer",
		DENCH19MO:"Monitor",
		DENCH24MO:"Monitor",
		DE55CDNPR:"Printer",
		DE130CNPR:"Printer",
		DE460DNPR:"Printer",
		DE760DNPR:"Printer",
		DE350DNPR:"Printer",
		DE5230NPR:"Printer",
		DET1650CO:"Computer",
		LOMK710KE:"KeyboardMouse",
		LOM705KE:"KeyboardMouse",
		LOK350KE:"KeyboardMouse",
		LOM110KE:"KeyboardMouse",
		NE105NASW:"Switch",
		NEFS105SW:"Switch",
		PLVISTAAM:"Amp",
		PLHW261HE:"Headset",
		POIP321PH:"Phone",
		POIP601PH:"Phone",
		POP5000PH:"Phone",
		POIP320PH:"Phone",
		POIP355PH:"Phone",
		SHUOS60DA:"Dashboard",
		SOVIA42DA:"Dashboard",
		DEDVI2DO:"DockingStation",
		DEDVI1DO:"DockingStation",
		DETABLECH:"Charger",
		SAART55DA:"Dashboard",
		POIP650PH:"Phone",
		POIP650PH:"Phone",
		APRBOLTMO:"Monitor",
		APMAC21CO:"Computer",
		APMAC27CO:"Computer",
		BOBOOKCO:"Computer",
		DET3500CO:"Computer",
		DET7500CO:"Computer",
		APACPROCO:"Computer",
		DET1650CO:"Computer",
		APAIR11CO:"Computer",
		DEER720SE:"Server",
		DEK1100SE:"Server",
		DEE1950SE:"Server",
		DEER510SE:"Server",
		DEK2100SE:"Server",
		DEER610SE:"Server",
		DED1000SE:"Server",
		DEE2950SE:"Server",
		HPDL360SE:"Server",
		DE6110XSE:"Server",
		DEE2850SE:"Server",
		DE3200ISE:"Server",
		DET1700CO:"Computer",
		PLM22A:"Amp",
		AMB13L:"Computer",
		AMB15L:"Computer",
		AMBP15RL:"Computer",
		AMBP13RL:"Computer",
		AMBA13L:"Computer",
		AMMD:"Computer",
		DO7010D:"Computer",
		DO790D:"Computer",
		DE6530CO:"Computer",
		DE6520CO:"Computer",
		DO780D:"Computer",
		SBrav42DB:"Dashboard",
		SHaqu60DB:"Dashboard",
		PLM261H:"Headset",
		LMK700K:"KeyboardMouse",
		LM705MO:"KeyboardMouse",
		LK350K:"KeyboardMouse",
		LM110MO:"KeyboardMouse",
		A27M:"Monitor",
		D19M:"Monitor",
		D24M:"Monitor",
		P321PH:"Phone",
		P601PH:"Phone",
		P5000PH:"Phone",
		D2155PR:"Printer",
		D3130PR:"Printer",
		DB3460PR:"Printer",
		DC3760dnPR:"Printer",
		D5350dnPR:"Printer",
		D5230nPR:"Printer",
		NGS105S:"Switch",
		NFS105S:"Switch",
		DT1650D:"Computer",
		p320ph:"Phone",
		LON231WE:"WebCam"





	};
	return { 
			returntype: function(code){
				return Type[code];
			}
	}
	
}]);
app.factory('AssetTable', [function () {
	var AssetTable = []

	return {
		pushtoAssetTable: function(data){
			AssetTable.push(data);

		},
		getAssetTable: function(){
			return AssetTable;
		}


	};
}]);

app.config(['$routeProvider','$locationProvider', function ($routeProvider,$locationProvider) {
	$routeProvider
		.when('/',{
			templateUrl: '/html/home.html',
			controller: 'homeCtrl'
		})
		.when('/modules/assetform',{
			templateUrl: '/html/assetform.html',
			controller: 'assestformCtrl'

		})
		.when('/modules/location',{
			templateUrl: '/html/location.html',
			controller: 'locationCtrl'
		})
		.otherwise({ redirectTo: 'home.html' });
}]);

app.controller('homeCtrl', ['$scope', function ($scope) {
	$scope.usernames =[
		{name: "bcs_AAwadalla.png"},
		{name: "bcs_abaddour.png"},
		{name: "bcs_abaset.png"},
		{name: "bcs_ABorean.png"},
		{name: "bcs_aburk.png"},
		{name: "bcs_AByrd.png"},
		{name: "bcs_adahlin.png"},
		{name: "bcs_adix.png"},
		{name: "bcs_Aduncan.png"},
		{name: "bcs_aedwards.png"},
		{name: "bcs_agreen.png"},
		{name: "bcs_ahadley.png"},
		{name: "bcs_ahill.png"},
		{name: "bcs_akampman.png"},
		{name: "bcs_akenkeremath.png"},
		{name: "bcs_akim.png"},
		{name: "bcs_Aleggett.png"},
		{name: "bcs_aloloyan.png"},
		{name: "bcs_alovell.png"},
		{name: "bcs_amastromarino.png"},
		{name: "bcs_amintzell.png"},
		{name: "bcs_anader.png"},
		{name: "bcs_aphilogene.png"},
		{name: "bcs_ARamaiya.png"},
		{name: "bcs_Areid.png"},
		{name: "bcs_arichards.png"},
		{name: "bcs_ashumaker.png"},
		{name: "bcs_asingh.png"},
		{name: "bcs_astarman.png"},
		{name: "bcs_astrub.png"},
		{name: "bcs_atalavera.png"},
		{name: "bcs_Atrowell.png"},
		{name: "bcs_avasquez.png"},
		{name: "bcs_awatson.png"},
		{name: "bcs_awelch.png"},
		{name: "bcs_awest.png"},
		{name: "bcs_azadran.png"},
		{name: "bcs_azaidan.png"},
		{name: "bcs_bbarrera.png"},
		{name: "bcs_bbrooks.png"},
		{name: "bcs_bcardillo.png"},
		{name: "bcs_BCarter.png"},
		{name: "bcs_bdorsey.png"},
		{name: "bcs_bfahim.png"},
		{name: "bcs_bjames.png"},
		{name: "bcs_BJones.png"},
		{name: "bcs_bjordan.png"},
		{name: "bcs_Bkatz.png"},
		{name: "bcs_bmace.png"},
		{name: "bcs_Bpeizer.png"},
		{name: "bcs_brictor.png"},
		{name: "bcs_bscherr.png"},
		{name: "bcs_bsilva.png"},
		{name: "bcs_BSymonds1.png"},
		{name: "bcs_Btapp.png"},
		{name: "bcs_BTewolde.png"},
		{name: "bcs_candrews.png"},
		{name: "bcs_cboinville.png"},
		{name: "bcs_cbrown.png"},
		{name: "bcs_ccanty.png"},
		{name: "bcs_Cfitzpatrick.png"},
		{name: "bcs_chodnett.png"},
		{name: "bcs_cjones3.png"},
		{name: "bcs_clittle.png"},
		{name: "bcs_cmackin.png"},
		{name: "bcs_cmcclintock.png"},
		{name: "bcs_cmunroe.png"},
		{name: "bcs_cnelson.png"},
		{name: "bcs_cpark.png"},
		{name: "bcs_cpatrizio.png"},
		{name: "bcs_CPeele.png"},
		{name: "bcs_crandolph2.png"},
		{name: "bcs_cschrager.png"},
		{name: "bcs_csekelsky.png"},
		{name: "bcs_Cstumpf.png"},
		{name: "bcs_cswanberg.png"},
		{name: "bcs_ctobias.png"},
		{name: "bcs_Cvickery.png"},
		{name: "bcs_cvillar.png"},
		{name: "bcs_cwilley.png"},
		{name: "bcs_cyoung.png"},
		{name: "bcs_dbadamirza.png"},
		{name: "bcs_dbaker.png"},
		{name: "bcs_dbuss.png"},
		{name: "bcs_dclark.png"},
		{name: "bcs_dfarmer.png"},
		{name: "bcs_dferguson.png"},
		{name: "bcs_dfowler.png"},
		{name: "bcs_dfreshwater.png"},
		{name: "bcs_DHeyman.png"},
		{name: "bcs_dholt.png"},
		{name: "bcs_dmccray.png"},
		{name: "bcs_dmoss.png"},
		{name: "bcs_dmullaney.png"},
		{name: "bcs_dsanders.png"},
		{name: "bcs_dsinicrope.png"},
		{name: "bcs_dsnell.png"},
		{name: "bcs_dson.png"},
		{name: "bcs_dwalker.png"},
		{name: "bcs_ealcindor.png"},
		{name: "bcs_EAraps.png"},
		{name: "bcs_ECativo.png"},
		{name: "bcs_edieguez.png"},
		{name: "bcs_eencarnacion.png"},
		{name: "bcs_eshelton.png"},
		{name: "bcs_esoto.png"},
		{name: "bcs_ethomson.png"},
		{name: "bcs_FHarris.png"},
		{name: "bcs_flopez.png"},
		{name: "bcs_fmorel.png"},
		{name: "bcs_FPerez.png"},
		{name: "bcs_gashe.png"},
		{name: "bcs_gbregon.png"},
		{name: "bcs_gcho.png"},
		{name: "bcs_gcotto.png"},
		{name: "bcs_ghogge.png"},
		{name: "bcs_gjorro.png"},
		{name: "bcs_gkouri.png"},
		{name: "bcs_glefranc.png"},
		{name: "bcs_gllames.png"},
		{name: "bcs_GSantore.png"},
		{name: "bcs_gsims.png"},
		{name: "bcs_gwilson.png"},
		{name: "bcs_hchaudhary.png"},
		{name: "bcs_HOCallaghan.png"},
		{name: "bcs_hvaldes.png"},
		{name: "bcs_ierceg.png"},
		{name: "bcs_jabernathy.png"},
		{name: "bcs_jaddison.png"},
		{name: "bcs_jalborna.png"},
		{name: "bcs_jbalogh.png"},
		{name: "bcs_JBenjamin.png"},
		{name: "bcs_JBissett.png"},
		{name: "bcs_jbotzer.png"},
		{name: "bcs_jbowen.png"},
		{name: "bcs_jbrown.png"},
		{name: "bcs_jbrumberg.png"},
		{name: "bcs_jbuzhardt.png"},
		{name: "bcs_jcasebere.png"},
		{name: "bcs_jdick.png"},
		{name: "bcs_JDugger.png"},
		{name: "bcs_jdunne.png"},
		{name: "bcs_jdye.png"},
		{name: "bcs_jevans.png"},
		{name: "bcs_JFrater.png"},
		{name: "bcs_jgavejian.png"},
		{name: "bcs_jgetz.png"},
		{name: "bcs_jgoda.png"},
		{name: "bcs_jgwilliam.png"},
		{name: "bcs_jhannula.png"},
		{name: "bcs_jhellen.png"},
		{name: "bcs_jheo.png"},
		{name: "bcs_jhoward.png"},
		{name: "bcs_jhynes.png"},
		{name: "bcs_jinman.png"},
		{name: "bcs_jjarkowski.png"},
		{name: "bcs_jkatzowitz.png"},
		{name: "bcs_jkeene.png"},
		{name: "bcs_jkeo.png"},
		{name: "bcs_jkim.png"},
		{name: "bcs_JLemus.png"},
		{name: "bcs_jlincoln.png"},
		{name: "bcs_jloerakker.png"},
		{name: "bcs_jmichie.png"},
		{name: "bcs_jmigliaccio.png"},
		{name: "bcs_Jmiletsky.png"},
		{name: "bcs_jmorales.png"},
		{name: "bcs_jpeterson.png"},
		{name: "bcs_jpierce.png"},
		{name: "bcs_jpierce2.png"},
		{name: "bcs_jquintanilla.png"},
		{name: "bcs_jrobison.png"},
		{name: "bcs_jschwartz1.png"},
		{name: "bcs_JSeepersaud.png"},
		{name: "bcs_jshull.png"},
		{name: "bcs_jsniezek.png"},
		{name: "bcs_JTaylor.png"},
		{name: "bcs_jwest.png"},
		{name: "bcs_JZerbonia.png"},
		{name: "bcs_kamin.png"},
		{name: "bcs_KAnsari.png"},
		{name: "bcs_KBest.png"},
		{name: "bcs_kbish.png"},
		{name: "bcs_kboodhoo.png"},
		{name: "bcs_KBurke.png"},
		{name: "bcs_kburt.png"},
		{name: "bcs_kclassen.png"},
		{name: "bcs_kcollinson.png"},
		{name: "bcs_kcotner.png"},
		{name: "bcs_kdement.png"},
		{name: "bcs_kdemine.png"},
		{name: "bcs_kferrell.png"},
		{name: "bcs_kfoutah.png"},
		{name: "bcs_kgoebel.png"},
		{name: "bcs_khewitt.png"},
		{name: "bcs_khudson.png"},
		{name: "bcs_kjanda.png"},
		{name: "bcs_kjones.png"},
		{name: "bcs_klawshe.png"},
		{name: "bcs_kmodl.png"},
		{name: "bcs_koneill.png"},
		{name: "bcs_kroyal.png"},
		{name: "bcs_krynex.png"},
		{name: "bcs_kschweikart.png"},
		{name: "bcs_ktaylor.png"},
		{name: "bcs_kthomas.png"},
		{name: "bcs_kveline.png"},
		{name: "bcs_kwalker.png"},
		{name: "bcs_kwoestman.png"},
		{name: "bcs_LAlfaro.png"},
		{name: "bcs_LChapman.png"},
		{name: "bcs_lderueda.png"},
		{name: "bcs_LHankin.png"},
		{name: "bcs_lhuffman.png"},
		{name: "bcs_lkurimsky.png"},
		{name: "bcs_lloyd.png"},
		{name: "bcs_lnolan.png"},
		{name: "bcs_logundijo.png"},
		{name: "bcs_lperkins.png"},
		{name: "bcs_lphan.png"},
		{name: "bcs_lrivera.png"},
		{name: "bcs_LShaffer.png"},
		{name: "bcs_lwelch.png"},
		{name: "bcs_lwilkins.png"},
		{name: "bcs_lwilliams.png"},
		{name: "bcs_MAhart.png"},
		{name: "bcs_malvarado.png"},
		{name: "bcs_malvarez.png"},
		{name: "bcs_mashmore.png"},
		{name: "bcs_mbailey.png"},
		{name: "bcs_mchapman.png"},
		{name: "bcs_mcherka.png"},
		{name: "bcs_mcurd.png"},
		{name: "bcs_mdaniel.png"},
		{name: "bcs_mdavis.png"},
		{name: "bcs_mdavis2.png"},
		{name: "bcs_mdowdy.png"},
		{name: "bcs_mfox.png"},
		{name: "bcs_mgills.png"},
		{name: "bcs_mguerra.png"},
		{name: "bcs_mhassan.png"},
		{name: "bcs_mholmes.png"},
		{name: "bcs_MJones.png"},
		{name: "bcs_MKang.png"},
		{name: "bcs_mnguyen.png"},
		{name: "bcs_mpiczon.png"},
		{name: "bcs_MPorter.png"},
		{name: "bcs_mrocha.png"},
		{name: "bcs_msalaam.png"},
		{name: "bcs_mscherrer.png"},
		{name: "bcs_msmith.png"},
		{name: "bcs_mstrein.png"},
		{name: "bcs_mtran.png"},
		{name: "bcs_mward.png"},
		{name: "bcs_nbrakebill.png"},
		{name: "bcs_ngrist.png"},
		{name: "bcs_nharless.png"},
		{name: "bcs_njarmuth.png"},
		{name: "bcs_nlambright.png"},
		{name: "bcs_nmusick.png"},
		{name: "bcs_oburgos.png"},
		{name: "bcs_odornano.png"},
		{name: "bcs_pabuto.png"},
		{name: "bcs_padams.png"},
		{name: "bcs_paguilar.png"},
		{name: "bcs_pdeprefontaine.png"},
		{name: "bcs_pdionisio.png"},
		{name: "bcs_pfallon.png"},
		{name: "bcs_PKhrizman.png"},
		{name: "bcs_PLawrence.png"},
		{name: "bcs_pmausner.png"},
		{name: "bcs_pmccalla.png"},
		{name: "bcs_pmittal.png"},
		{name: "bcs_pmunoz.png"},
		{name: "bcs_pobering.png"},
		{name: "bcs_POboite.png"},
		{name: "bcs_ppearson.png"},
		{name: "bcs_progers.png"},
		{name: "bcs_ptran.png"},
		{name: "bcs_pwilliams.png"},
		{name: "bcs_RAsmar.png"},
		{name: "bcs_rclark.png"},
		{name: "bcs_rcohen.png"},
		{name: "bcs_rdalmas.png"},
		{name: "bcs_Rdawkins.png"},
		{name: "bcs_rgralka.png"},
		{name: "bcs_rgrant.png"},
		{name: "bcs_RHutchins.png"},
		{name: "bcs_RPinkney.png"},
		{name: "bcs_rpompeo.png"},
		{name: "bcs_RSchmidt.png"},
		{name: "bcs_rshepherd.png"},
		{name: "bcs_rsteinberg.png"},
		{name: "bcs_RThomson.png"},
		{name: "bcs_RUmberger.png"},
		{name: "bcs_SBastati.png"},
		{name: "bcs_sbatky.png"},
		{name: "bcs_sbuffalow.png"},
		{name: "bcs_scaswell.png"},
		{name: "bcs_scene.png"},
		{name: "bcs_sdeyoe.png"},
		{name: "bcs_sdimond.png"},
		{name: "bcs_sedouard.png"},
		{name: "bcs_sgrant.png"},
		{name: "bcs_SGrant2.png"},
		{name: "bcs_sgrassmann.png"},
		{name: "bcs_sharris.png"},
		{name: "bcs_sherrador.png"},
		{name: "bcs_shicks.png"},
		{name: "bcs_sjaved.png"},
		{name: "bcs_sjohn.png"},
		{name: "bcs_skanamine.png"},
		{name: "bcs_slee.png"},
		{name: "bcs_smason.png"},
		{name: "bcs_smutersbaugh.png"},
		{name: "bcs_SOliver.png"},
		{name: "bcs_Sreifsnyder.png"},
		{name: "bcs_sseawell.png"},
		{name: "bcs_ssmylie.png"},
		{name: "bcs_SSpriggs.png"},
		{name: "bcs_stheys.png"},
		{name: "bcs_STrehan.png"},
		{name: "bcs_swaddell.png"},
		{name: "bcs_swalch.png"},
		{name: "bcs_swillard.png"},
		{name: "bcs_szander.png"},
		{name: "bcs_tabul-qasim.png"},
		{name: "bcs_tbeyene.png"},
		{name: "bcs_tbowman.png"},
		{name: "bcs_tboyd.png"},
		{name: "bcs_tboynes.png"},
		{name: "bcs_tchipani.png"},
		{name: "bcs_TDixon.png"},
		{name: "bcs_tfalaiye.png"},
		{name: "bcs_tgross.png"},
		{name: "bcs_thall.png"},
		{name: "bcs_Tharmon.png"},
		{name: "bcs_tjacobs.png"},
		{name: "bcs_tlee.png"},
		{name: "bcs_TMarshall.png"},
		{name: "bcs_tmeyer.png"},
		{name: "bcs_tnguyen.png"},
		{name: "bcs_TPaxman.png"},
		{name: "bcs_truel.png"},
		{name: "bcs_TTaylor.png"},
		{name: "bcs_twhelan.png"},
		{name: "bcs_uhassan.png"},
		{name: "bcs_UKhan.png"},
		{name: "bcs_VGalloway.png"},
		{name: "bcs_vsaponara.png"},
		{name: "bcs_wbabcock.png"},
		{name: "bcs_wbennett.png"},
		{name: "bcs_wchu.png"},
		{name: "bcs_wmoskowitz.png"},
		{name: "bcs_wsaunders.png"},
		{name: "bcs_ykang.png"},
		{name: "bcs_zbartosik.png"}
		];
}]);
app.controller('assestformCtrl', ['$scope','$location','AssetCodeMake','AssetCodeModel','AssetCodeType', 'AssetTable','$http',
	function ($scope, $location, AssetCodeMake, AssetCodeModel, AssetCodeType, AssetTable, $http) {
		$scope.Assets = AssetTable.getAssetTable();
		$scope.showstuff = true;
		
		$scope.makemodel = function(){			
				$scope.assetmake = AssetCodeMake.returnmake($scope.AssetCode);			
				$scope.assetmodel = AssetCodeModel.returnmodel($scope.AssetCode);
				$scope.assettype = AssetCodeType.returntype($scope.AssetCode);
				angular.element('#makemodel').removeAttr("disabled")
				$scope.showstuff = false;
		}
		$scope.submit = function(){
			$scope.showstuff = true;
			$scope.asset = {
				assetid: $scope.AssetNum,
				make: $scope.assetmake,
				model: $scope.assetmodel,
				type: $scope.assettype,
				serial: $scope.Serial,
				custodian: $scope.Custodian,
				location: $scope.locate
			}
			AssetTable.pushtoAssetTable($scope.asset);
			$scope.AssetNum = "";
			$scope.AssetCode = "";
			$scope.Serial = "";
			document.getElementById('AssetNum').focus();
			
		}	
	}]);
app.controller('locationCtrl', ['$scope', function ($scope) {
	$scope.location = [
						{name:"1568 - BREAK ROOM - 100.png"},
{name:"1568 - BREAK ROOM - 200.png"},
{name:"1568 - BREAK ROOM - 300.png"},
{name:"1568 - BREAK ROOM - 301.png"},
{name:"1568 - BREAK ROOM - 400.png"},
{name:"1568 - CR - Aspen.png"},
{name:"1568 - CR - Batcave.png"},
{name:"1568 - CR - Fishbowl.png"},
{name:"1568 - CR - Killington.png"},
{name:"1568 - CR - Mammoth.png"},
{name:"1568 - CR - Pico.png"},
{name:"1568 - CR - Snowbird.png"},
{name:"1568 - CR - Steamboat.png"},
{name:"1568 - CR - Stowe.png"},
{name:"1568 - CR - Sundance.png"},
{name:"1568 - CR - Training Room.png"},
{name:"1568 - CR - Whistler.png"},
{name:"1568 - CR - Whitetail.png"},
{name:"1568 - CUBES - 100.png"},
{name:"1568 - CUBES - 101.png"},
{name:"1568 - CUBES - 200.png"},
{name:"1568 - CUBES - 201.png"},
{name:"1568 - CUBES - Compliance.png"},
{name:"1568 - FLOOR - 01.png"},
{name:"1568 - FLOOR - 02.png"},
{name:"1568 - FLOOR - 03.png"},
{name:"1568 - FLOOR - 04.png"},
{name:"1568 - OFFICE - 04.png"},
{name:"1568 - OFFICE - 100 - 03.png"},
{name:"1568 - OFFICE - 100 - O1.png"},
{name:"1568 - OFFICE - 100 - O2.png"},
{name:"1568 - OFFICE - 101.png"},
{name:"1568 - OFFICE - 200 - O1.png"},
{name:"1568 - OFFICE - 200 - O2.png"},
{name:"1568 - OFFICE - 300 - O1.png"},
{name:"1568 - OFFICE - 300 - O2.png"},
{name:"1568 - OFFICE - 300 - O3.png"},
{name:"1568 - OFFICE - 300 - O4.png"},
{name:"1568 - OFFICE - 300 - O5.png"},
{name:"1568 - OFFICE - Front Desk.png"},
{name:"1568 - OFFICE - S100 - O4.png"},
{name:"1568 - SERVER - First Floor.png"},
{name:"1568 - SERVER - Fourth Floor.png"},
{name:"1568 - STORAGE - First Floor Electrical.png"},
{name:"1568 - STORAGE - Fourth Floor Electrical.png"},
{name:"1568 - STORAGE - Second Floor Electrical.png"},
{name:"1568 - STORAGE - Server.png"},
{name:"1568 - STORAGE - Third Floor Electrical.png"},
{name:"1568 - STORAGE - Third Floor.png"},
{name:"1568 - SUITE - 100.png"},
{name:"1568 - SUITE - 101.png"},
{name:"1568 - SUITE - 200.png"},
{name:"1568 - SUITE - 201.png"},
{name:"1568 - SUITE - 300.png"},
{name:"1568 - SUITE - 303.png"},
{name:"1568 - SUITE - 400.png"},
{name:"1568 - SUITE - 401.png"},
{name:"1568 - SUITE - 402.png"},
{name:"1595 - CR - Big Sky.png"},
{name:"1595 - CR - Big Squaw.png"},
{name:"1595 - CR - Brekinridge.png"},
{name:"1595 - CR - Keystone.png"},
{name:"1595 - CR - Panorama.png"},
{name:"1595 - CR - Powderhorn.png"},
{name:"1595 - CR - Snowbasin.png"},
{name:"1595 - CR - Snowmass.png"},
{name:"1595 - CR - Timberline.png"},
{name:"1595 - CR - Titus.png"},
{name:"1595 - CR - Vail.png"},
{name:"1595 - CR - Vals.png"},
{name:"1595 - CR - WISP.png"},
{name:"1595 - CUBES - CST A.png"},
{name:"1595 - CUBES - CSVS A.png"},
{name:"1595 - CUBES - FIN A.png"},
{name:"1595 - CUBES - Fulfillment.png"},
{name:"1595 - CUBES - HR A.png"},
{name:"1595 - CUBES - IT.png"},
{name:"1595 - CUBES - MKTG A.png"},
{name:"1595 - CUBES - MKTG B.png"},
{name:"1595 - FLOOR - 01 .png"},
{name:"1595 - FLOOR - 07.png"},
{name:"1595 - OFFICE - 01.png"},
{name:"1595 - OFFICE - 010.png"},
{name:"1595 - OFFICE - 02.png"},
{name:"1595 - OFFICE - 03.png"},
{name:"1595 - OFFICE - 04.png"},
{name:"1595 - OFFICE - 05.png"},
{name:"1595 - OFFICE - 06.png"},
{name:"1595 - OFFICE - 07.png"},
{name:"1595 - OFFICE - 08.png"},
{name:"1595 - OFFICE - 11.png"},
{name:"1595 - OFFICE - 110 - O2.png"},
{name:"1595 - OFFICE - 110 - O3.png"},
{name:"1595 - OFFICE - 12.png"},
{name:"1595 - OFFICE - 13.png"},
{name:"1595 - OFFICE - 14.png"},
{name:"1595 - OFFICE - 15.png"},
{name:"1595 - OFFICE - 16.png"},
{name:"1595 - OFFICE - 17.png"},
{name:"1595 - OFFICE - 18.png"},
{name:"1595 - OFFICE - 19.png"},
{name:"1595 - OFFICE - 20.png"},
{name:"1595 - OFFICE - 21.png"},
{name:"1595 - OFFICE - 22.png"},
{name:"1595 - OFFICE - 23.png"},
{name:"1595 - OFFICE - 24.png"},
{name:"1595 - OFFICE - 25.png"},
{name:"1595 - OFFICE - 26.png"},
{name:"1595 - SERVER - 700.png"},
{name:"1595 - SUITE - 105.png"},
{name:"1595 - SUITE - 110.png"},
{name:"1595 - SUITE - 700.png"}

						];
}])